version: "3"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:10
    ports:
      - 443:443
    restart: always
    volumes:
      - wp_data:/data/www
    networks:
      - inception
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPSW=${DBPSW}
    image: wordpress:10
    restart: always
    # tty: true
    # stdin_open: true
    volumes:
      - wp_data:/data/www
    networks:
      - inception
    environment:
      - DBNAME
      - DBUSER
      - DBPSW
  mariadb:
    container_name: mariadb
    build:
      context:  ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPSW=${DBPSW}
        - WPADM=${WPADM}
        - WPADMPSW=${WPADMPSW}
        - WPUSR=${WPUSR}
        - WPUSRPSW=${WPUSRPSW}
    image: mariadb:10
    restart: always
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - inception
networks:
  inception:
    driver: bridge
volumes:
  wp_data:
    driver: local
    name: wp_data
    driver_opts:
      type: none
      device: ~/data/wordpress_app
      o: bind
  wp_db:
    driver: local
    name: wp_db
    driver_opts:
      type: none
      device: ~/data/wordpress_db
      o: bind