version: "3"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:10
    ports:
      - 80:80
    volumes:
      - wp_data:/data/www
    networks:
      - front
      - back
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPSW=${DBPSW}
    image: wordpress:10
    ports:
      - 9000:9000
    tty: true
    stdin_open: true
    volumes:
      - wp_data:/data/www
    networks:
      - back
    environment:
      - DBNAME
      - DBUSER
      - DBPSW
  mariadb:
    container_name: mariadb
    build:
      context:  ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPSW=${DBPSW}
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - back
networks:
  front: {}
  back: {}
volumes:
  wp_data:
    driver: local
    name: wp_data
    driver_opts:
      type: none
      device: ./wordpress_app
      o: bind
  wp_db:
    driver: local
    name: wp_db
    driver_opts:
      type: none
      device: ./wordpress_db
      o: bind