version: "3"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:10
    ports:
      - 443:443
    restart: always
    volumes:
      - wp_data:/data/www
    networks:
      - inception
    depends_on:
      - wordpress
      - mariadb
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:10
    restart: always
    volumes:
      - wp_data:/data/www
    networks:
      - inception
    depends_on:
      - mariadb
    environment:
      - DBNAME
      - DBUSER
      - DBPSW
      - WPADM
      - WPADMPSW
      - WPUSR
      - WPUSRPSW
  mariadb:
    container_name: mariadb
    build:
      context:  ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DBUSER=${DBUSER}
        - DBPSW=${DBPSW}
        - DBROOTPSW=${DBROOTPSW}
    image: mariadb:10
    restart: always
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - inception
networks:
  inception:
    driver: bridge
volumes:
  wp_data:
    driver: local
    name: wp_data
    driver_opts:
      type: none
      device: ~/hde-camp/data/wordpress_app
      o: bind
  wp_db:
    driver: local
    name: wp_db
    driver_opts:
      type: none
      device: ~/hde-camp/data/wordpress_db
      o: bind