version: "3"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:10
    ports:
      - 443:443
#Bonus Ports
      - "20-21:20-21" #ftpserver
      - 444:444 #adminer
      - "27017:27017" #mongodb
      - "80:80" #expressjs
    restart: always
    volumes:
      - wp_data:/data/www
      - adminer:/data/adminer
    networks:
      - inception
    depends_on:
      - wordpress
      - mariadb
      - redis
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:10
    restart: always
    volumes:
      - wp_data:/data/www
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    environment:
      - DBNAME
      - DBUSER
      - DBPSW
      - WPADM
      - WPADMPSW
      - WPUSR
      - WPUSRPSW
  mariadb:
    container_name: mariadb
    build:
      context:  ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DBUSER=${DBUSER}
        - DBPSW=${DBPSW}
        - DBROOTPSW=${DBROOTPSW}
    image: mariadb:10
    restart: always
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - inception
#Bonus services
  redis:
    container_name: redis
    build:
      context:  ./requirements/bonus/redis
      dockerfile: Dockerfile
    image: redis:10
    restart: always
    networks:
      - inception
  ftpserver:
    container_name: ftpserver
    build:
      context:  ./requirements/bonus/ftpserver
      dockerfile: Dockerfile
    image: ftpserver:10
    restart: always
    volumes:
      - wp_data:/data/ftp
    networks:
      - inception
  adminer:
    container_name: adminer
    build:
      context:  ./requirements/bonus/adminer
      dockerfile: Dockerfile
    image: adminer:10
    restart: always
    volumes:
      - adminer:/data/adminer
    networks:
      - inception
  mongodb:
    container_name: mongodb
    build:
      context:  ./requirements/bonus/mongodb
      dockerfile: Dockerfile
    image: mongodb:10
    # ports:
      # - 27017:27017
    restart: always
    volumes:
      - mongodb:/data/db
    networks:
      - inception
  expressjs:
    container_name: expressjs
    build:
      context:  ./requirements/bonus/expressjs
      dockerfile: Dockerfile
    image: expressjs:10
    restart: always
    networks:
      - inception
networks:
  inception:
    name: inception
    driver: bridge
volumes:
  wp_data:
    driver: local
    name: wp_data
    driver_opts:
      type: none
      device: ~/hde-camp/data/wordpress_app
      o: bind
  wp_db:
    driver: local
    name: wp_db
    driver_opts:
      type: none
      device: ~/hde-camp/data/wordpress_db
      o: bind
#Bonus Volumes
  adminer:
    driver: local
    name: adminer
    driver_opts:
      type: none
      device: ~/hde-camp/data/adminer
      o: bind
  mongodb:
    driver: local
    name: mongodb
    driver_opts:
      type: none
      device: ~/hde-camp/data/mongodb
      o: bind