#https://bobcares.com/blog/docker-compose-nginx-php-fpm-mysql-wordpress/
version: "3"
services:
  nginx:
    container_name: nginx_inception
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - wp_data:/data/www
    networks:
      - front
      - back
    depends_on:
      - wordpress
  wordpress:
    container_name: wp_inception
    build: ./wordPress_php_fpm
    ports:
      - 9000:9000
    tty: true
    stdin_open: true
    volumes:
      - wp_data:/data/www
    networks:
      - back
  mariadb:
    container_name: mariadb
    build: ./mariadb
    ports:
      - 3306:3306
    networks:
      - back
networks:
  front: {}
  back: {}
volumes:
  wp_data:
    driver: local
    driver_opts:
      device: ./wordpress_data
      o: bind
      type: none
    name: wp_data