# nginx docs https://nginx.org/en/docs/
# nginx recipe https://www.nginx.com/resources/wiki/start/topics/recipes/wordpress/
# https://www.cyberciti.biz/faq/how-to-install-nginx-web-server-on-alpine-linux/
FROM alpine:3.15

RUN apk update && apk upgrade
RUN apk add nginx

CMD []
